var products = [
  {
    "ID":23,
    "GroupName":"PhotoCreate-Mugs",
    "ItemName":"Mugs",
    "Description":"Standard Mug - Right Handed",
    "UnitPrice":19.95,
    "Postage":5.98,
    "PCCode":4684,
    "DisplayOrder":01,
    "ItemMediaType":"",
    "MaxQuantity":"0",
    "DescriptionURL":"",
    "CostCode":"P",
    "PublisherTemplate":"",
    "CropRatio":"",
    "XmPieCampaignID":"",
    "XmPieDocumentID":"",
    "WidthMM":93,
    "HeightMM":79,
    "FWidthMM":93,
    "FHeightMM":79,
    "DPI":300,
    "PixW":1098,
    "PixH":933,
    "Price":"0"
  },
  {
    "ID":24,
    "GroupName":"PhotoCreate-Mugs",
    "ItemName":"Mugs",
    "Description":"Standard Mug - Left Handed",
    "UnitPrice":19.95,
    "Postage":5.98,
    "PCCode":4685,
    "DisplayOrder":02,
    "ItemMediaType":"",
    "MaxQuantity":"0",
    "DescriptionURL":"",
    "CostCode":"P",
    "PublisherTemplate":"",
    "CropRatio":"",
    "XmPieCampaignID":"",
    "XmPieDocumentID":"",
    "WidthMM":93,
    "HeightMM":79,
    "FWidthMM":93,
    "FHeightMM":79,
    "DPI":300,
    "PixW":1098,
    "PixH":933,
    "Price":"0"
  },
  {
    "ID":25,
    "GroupName":"PhotoCreate-Canvas Prints",
    "ItemName":"Canvas Prints",
    "Description":"16x20 Canvas Print",
    "UnitPrice":99.00,
    "Postage":12.19,
    "PCCode":140,
    "DisplayOrder":02,
    "ItemMediaType":"",
    "MaxQuantity":"0",
    "DescriptionURL":"",
    "CostCode":"P",
    "PublisherTemplate":"",
    "CropRatio":"",
    "XmPieCampaignID":"",
    "XmPieDocumentID":"",
    "WidthMM":465,
    "HeightMM":560,
    "FWidthMM":400,
    "FHeightMM":500,
    "DPI":150,
    "PixW":2746,
    "PixH":3307,
    "Price":"0"
  },
  {
    "ID":26,
    "GroupName":"PhotoCreate-Canvas Prints",
    "ItemName":"Canvas Prints",
    "Description":"20x30 Canvas Print",
    "UnitPrice":149.00,
    "Postage":14.46,
    "PCCode":141,
    "DisplayOrder":03,
    "ItemMediaType":"",
    "MaxQuantity":"0",
    "DescriptionURL":"",
    "CostCode":"P",
    "PublisherTemplate":"",
    "CropRatio":"",
    "XmPieCampaignID":"",
    "XmPieDocumentID":"",
    "WidthMM":565,
    "HeightMM":815,
    "FWidthMM":500,
    "FHeightMM":750,
    "DPI":150,
    "PixW":3337,
    "PixH":4813,
    "Price":"0"
  },
  {
    "ID":27,
    "GroupName":"PhotoCreate-Canvas Prints",
    "ItemName":"Canvas Prints",
    "Description":"30x40 Canvas Print",
    "UnitPrice":219.00,
    "Postage":21.83,
    "PCCode":142,
    "DisplayOrder":04,
    "ItemMediaType":"",
    "MaxQuantity":"0",
    "DescriptionURL":"",
    "CostCode":"P",
    "PublisherTemplate":"",
    "CropRatio":"",
    "XmPieCampaignID":"",
    "XmPieDocumentID":"",
    "WidthMM":815,
    "HeightMM":1065,
    "FWidthMM":750,
    "FHeightMM":1000,
    "DPI":150,
    "PixW":4813,
    "PixH":6289,
    "Price":"0"
  },
  {
    "ID":28,
    "GroupName":"Photocreate-Photo Blocks",
    "ItemName":"Photo Blocks",
    "Description":"5x7 Black Photo Block (Gloss)",
    "UnitPrice":19.95,
    "Postage":6.17,
    "PCCode":4504,
    "DisplayOrder":01,
    "ItemMediaType":"",
    "MaxQuantity":"0",
    "DescriptionURL":"",
    "CostCode":"P",
    "PublisherTemplate":"",
    "CropRatio":"",
    "XmPieCampaignID":"",
    "XmPieDocumentID":"",
    "WidthMM":127,
    "HeightMM":178,
    "FWidthMM":124,
    "FHeightMM":174,
    "DPI":300,
    "PixW":1500,
    "PixH":2102,
    "Price":"0"
  },
  {
    "ID":29,
    "GroupName":"Photocreate-Photo Blocks",
    "ItemName":"Photo Blocks",
    "Description":"5x7 Black Photo Block (Matte)",
    "UnitPrice":19.95,
    "Postage":6.17,
    "PCCode":4505,
    "DisplayOrder":02,
    "ItemMediaType":"",
    "MaxQuantity":"0",
    "DescriptionURL":"",
    "CostCode":"P",
    "PublisherTemplate":"",
    "CropRatio":"",
    "XmPieCampaignID":"",
    "XmPieDocumentID":"",
    "WidthMM":127,
    "HeightMM":178,
    "FWidthMM":124,
    "FHeightMM":174,
    "DPI":300,
    "PixW":1500,
    "PixH":2102,
    "Price":"0"
  },
  {
    "ID":30,
    "GroupName":"Photocreate-Photo Blocks",
    "ItemName":"Photo Blocks",
    "Description":"5x7 White Photo Block (Gloss)",
    "UnitPrice":19.95,
    "Postage":6.17,
    "PCCode":4506,
    "DisplayOrder":03,
    "ItemMediaType":"",
    "MaxQuantity":"0",
    "DescriptionURL":"",
    "CostCode":"P",
    "PublisherTemplate":"",
    "CropRatio":"",
    "XmPieCampaignID":"",
    "XmPieDocumentID":"",
    "WidthMM":127,
    "HeightMM":178,
    "FWidthMM":124,
    "FHeightMM":174,
    "DPI":300,
    "PixW":1500,
    "PixH":2102,
    "Price":"0"
  },
  {
    "ID":31,
    "GroupName":"Photocreate-Photo Blocks",
    "ItemName":"Photo Blocks",
    "Description":"5x7 White Photo Block (Matte)",
    "UnitPrice":19.95,
    "Postage":6.17,
    "PCCode":4507,
    "DisplayOrder":04,
    "ItemMediaType":"",
    "MaxQuantity":"0",
    "DescriptionURL":"",
    "CostCode":"P",
    "PublisherTemplate":"",
    "CropRatio":"",
    "XmPieCampaignID":"",
    "XmPieDocumentID":"",
    "WidthMM":127,
    "HeightMM":178,
    "FWidthMM":124,
    "FHeightMM":174,
    "DPI":300,
    "PixW":1500,
    "PixH":2102,
    "Price":"0"
  },
  {
    "ID":32,
    "GroupName":"Photocreate-Photo Blocks",
    "ItemName":"Photo Blocks",
    "Description":"8x10 Black Photo Block (Gloss)",
    "UnitPrice":27.95,
    "Postage":8.79,
    "PCCode":4512,
    "DisplayOrder":05,
    "ItemMediaType":"",
    "MaxQuantity":"0",
    "DescriptionURL":"",
    "CostCode":"P",
    "PublisherTemplate":"",
    "CropRatio":"",
    "XmPieCampaignID":"",
    "XmPieDocumentID":"",
    "WidthMM":254,
    "HeightMM":203,
    "FWidthMM":245,
    "FHeightMM":197,
    "DPI":300,
    "PixW":3000,
    "PixH":2398,
    "Price":"0"
  },
  {
    "ID":33,
    "GroupName":"Photocreate-Photo Blocks",
    "ItemName":"Photo Blocks",
    "Description":"8x10 Black Photo Block (Matte)",
    "UnitPrice":27.95,
    "Postage":8.79,
    "PCCode":4513,
    "DisplayOrder":06,
    "ItemMediaType":"",
    "MaxQuantity":"0",
    "DescriptionURL":"",
    "CostCode":"P",
    "PublisherTemplate":"",
    "CropRatio":"",
    "XmPieCampaignID":"",
    "XmPieDocumentID":"",
    "WidthMM":254,
    "HeightMM":203,
    "FWidthMM":245,
    "FHeightMM":197,
    "DPI":300,
    "PixW":3000,
    "PixH":2398,
    "Price":"0"
  },
  {
    "ID":34,
    "GroupName":"Photocreate-Photo Blocks",
    "ItemName":"Photo Blocks",
    "Description":"8x10 White Photo Block (Gloss)",
    "UnitPrice":27.95,
    "Postage":8.79,
    "PCCode":4514,
    "DisplayOrder":07,
    "ItemMediaType":"",
    "MaxQuantity":"0",
    "DescriptionURL":"",
    "CostCode":"P",
    "PublisherTemplate":"",
    "CropRatio":"",
    "XmPieCampaignID":"",
    "XmPieDocumentID":"",
    "WidthMM":254,
    "HeightMM":203,
    "FWidthMM":245,
    "FHeightMM":197,
    "DPI":300,
    "PixW":3000,
    "PixH":2398,
    "Price":"0"
  },
  {
    "ID":35,
    "GroupName":"Photocreate-Photo Blocks",
    "ItemName":"Photo Blocks",
    "Description":"8x10 White Photo Block (Matte)",
    "UnitPrice":27.95,
    "Postage":8.79,
    "PCCode":4515,
    "DisplayOrder":08,
    "ItemMediaType":"",
    "MaxQuantity":"0",
    "DescriptionURL":"",
    "CostCode":"P",
    "PublisherTemplate":"",
    "CropRatio":"",
    "XmPieCampaignID":"",
    "XmPieDocumentID":"",
    "WidthMM":254,
    "HeightMM":203,
    "FWidthMM":245,
    "FHeightMM":197,
    "DPI":300,
    "PixW":3000,
    "PixH":2398,
    "Price":"0"
  },
  {
    "ID":36,
    "GroupName":"Photocreate-Ceramic Tiles",
    "ItemName":"Ceramic Tiles",
    "Description":"6x6 Ceramic Tile with Easel",
    "UnitPrice":29.95,
    "Postage":6.48,
    "PCCode":270,
    "DisplayOrder":01,
    "ItemMediaType":"",
    "MaxQuantity":"0",
    "DescriptionURL":"",
    "CostCode":"P",
    "PublisherTemplate":"",
    "CropRatio":"",
    "XmPieCampaignID":"",
    "XmPieDocumentID":"",
    "WidthMM":158,
    "HeightMM":158,
    "FWidthMM":152,
    "FHeightMM":152,
    "DPI":300,
    "PixW":1866,
    "PixH":1866,
    "Price":"0"
  },
  {
    "ID":37,
    "GroupName":"Photocreate-Glass Prints",
    "ItemName":"Glass Prints",
    "Description":"12x18 Glass Print",
    "UnitPrice":99.00,
    "Postage":16.86,
    "PCCode":1245,
    "DisplayOrder":01,
    "ItemMediaType":"",
    "MaxQuantity":"0",
    "DescriptionURL":"",
    "CostCode":"P",
    "PublisherTemplate":"",
    "CropRatio":"",
    "XmPieCampaignID":"",
    "XmPieDocumentID":"",
    "WidthMM":311,
    "HeightMM":463,
    "FWidthMM":305,
    "FHeightMM":457,
    "DPI":300,
    "PixW":3673,
    "PixH":5468,
    "Price":"0"
  },
  {
    "ID":38,
    "GroupName":"Photocreate-Glass Prints",
    "ItemName":"Glass Prints",
    "Description":"16x20 Glass Print",
    "UnitPrice":129.00,
    "Postage":19.57,
    "PCCode":1246,
    "DisplayOrder":02,
    "ItemMediaType":"",
    "MaxQuantity":"0",
    "DescriptionURL":"",
    "CostCode":"P",
    "PublisherTemplate":"",
    "CropRatio":"",
    "XmPieCampaignID":"",
    "XmPieDocumentID":"",
    "WidthMM":514,
    "HeightMM":412,
    "FWidthMM":508,
    "FHeightMM":406,
    "DPI":300,
    "PixW":6071,
    "PixH":4866,
    "Price":"0"
  },
  {
    "ID":39,
    "GroupName":"Photocreate-Glass Prints",
    "ItemName":"Glass Prints",
    "Description":"20x30 Glass Print",
    "UnitPrice":199.00,
    "Postage":28.01,
    "PCCode":1247,
    "DisplayOrder":03,
    "ItemMediaType":"",
    "MaxQuantity":"0",
    "DescriptionURL":"",
    "CostCode":"P",
    "PublisherTemplate":"",
    "CropRatio":"",
    "XmPieCampaignID":"",
    "XmPieDocumentID":"",
    "WidthMM":514,
    "HeightMM":768,
    "FWidthMM":508,
    "FHeightMM":762,
    "DPI":300,
    "PixW":6071,
    "PixH":9071,
    "Price":"0"
  },
  {
    "ID":40,
    "GroupName":"Photocreate-Glass Prints",
    "ItemName":"Glass Prints",
    "Description":"30x40 Glass Print",
    "UnitPrice":299.00,
    "Postage":46.58,
    "PCCode":1248,
    "DisplayOrder":04,
    "ItemMediaType":"",
    "MaxQuantity":"0",
    "DescriptionURL":"",
    "CostCode":"P",
    "PublisherTemplate":"",
    "CropRatio":"",
    "XmPieCampaignID":"",
    "XmPieDocumentID":"",
    "WidthMM":768,
    "HeightMM":1022,
    "FWidthMM":762,
    "FHeightMM":1016,
    "DPI":300,
    "PixW":9071,
    "PixH":12071,
    "Price":"0"
  },
  {
    "ID":41,
    "GroupName":"Photocreate-Greeting Cards - Blank Inside",
    "ItemName":"Greeting Cards - Blank Inside",
    "Description":"6x4 Greeting Card Portrait with envelope - 20 Pack",
    "UnitPrice":39.95,
    "Postage":3.32,
    "PCCode":619,
    "DisplayOrder":01,
    "ItemMediaType":"",
    "MaxQuantity":"0",
    "DescriptionURL":"",
    "CostCode":"P",
    "PublisherTemplate":"",
    "CropRatio":"",
    "XmPieCampaignID":"",
    "XmPieDocumentID":"",
    "WidthMM":204,
    "HeightMM":154,
    "FWidthMM":204,
    "FHeightMM":154,
    "DPI":300,
    "PixW":2409,
    "PixH":1819,
    "Price":"0"
  },
  {
    "ID":42,
    "GroupName":"Photocreate-Greeting Cards - Blank Inside",
    "ItemName":"Greeting Cards - Blank Inside",
    "Description":"5x7 Greeting Card Portrait with envelope - 20 Pack",
    "UnitPrice":49.95,
    "Postage":3.32,
    "PCCode":627,
    "DisplayOrder":02,
    "ItemMediaType":"",
    "MaxQuantity":"0",
    "DescriptionURL":"",
    "CostCode":"P",
    "PublisherTemplate":"",
    "CropRatio":"",
    "XmPieCampaignID":"",
    "XmPieDocumentID":"",
    "WidthMM":256,
    "HeightMM":180,
    "FWidthMM":256,
    "FHeightMM":180,
    "DPI":300,
    "PixW":3024,
    "PixH":2126,
    "Price":"0"
  },
  {
    "ID":43,
    "GroupName":"Photocreate-Novelty",
    "ItemName":"Sporty Drink Bottle 400mls",
    "Description":"Sporty Drink Bottle 400mls",
    "UnitPrice":24.95,
    "Postage":8.95,
    "PCCode":4689,
    "DisplayOrder":01,
    "ItemMediaType":"",
    "MaxQuantity":"0",
    "DescriptionURL":"",
    "CostCode":"P",
    "PublisherTemplate":"",
    "CropRatio":"",
    "XmPieCampaignID":"",
    "XmPieDocumentID":"",
    "WidthMM":93,
    "HeightMM":79,
    "FWidthMM":93,
    "FHeightMM":79,
    "DPI":300,
    "PixW":1098,
    "PixH":933,
    "Price":"0"
  },
  {
    "ID":44,
    "GroupName":"Photocreate-Metal Prints",
    "ItemName":"Metal Prints",
    "Description":"12x18 Metal Print - Gloss",
    "UnitPrice":99.00,
    "Postage":11.48,
    "PCCode":1275,
    "DisplayOrder":01,
    "ItemMediaType":"",
    "MaxQuantity":"0",
    "DescriptionURL":"",
    "CostCode":"P",
    "PublisherTemplate":"",
    "CropRatio":"",
    "XmPieCampaignID":"",
    "XmPieDocumentID":"",
    "WidthMM":311,
    "HeightMM":463,
    "FWidthMM":305,
    "FHeightMM":457,
    "DPI":300,
    "PixW":3673,
    "PixH":5468,
    "Price":"0"
  },
  {
    "ID":45,
    "GroupName":"Photocreate-Metal Prints",
    "ItemName":"Metal Prints",
    "Description":"16x20 Metal Print - Gloss",
    "UnitPrice":129.00,
    "Postage":12.12,
    "PCCode":1276,
    "DisplayOrder":02,
    "ItemMediaType":"",
    "MaxQuantity":"0",
    "DescriptionURL":"",
    "CostCode":"P",
    "PublisherTemplate":"",
    "CropRatio":"",
    "XmPieCampaignID":"",
    "XmPieDocumentID":"",
    "WidthMM":514,
    "HeightMM":412,
    "FWidthMM":508,
    "FHeightMM":406,
    "DPI":300,
    "PixW":6071,
    "PixH":4866,
    "Price":"0"
  },
  {
    "ID":46,
    "GroupName":"Photocreate-Metal Prints",
    "ItemName":"Metal Prints",
    "Description":"20x30 Metal Print - Gloss",
    "UnitPrice":199.00,
    "Postage":14.46,
    "PCCode":1277,
    "DisplayOrder":03,
    "ItemMediaType":"",
    "MaxQuantity":"0",
    "DescriptionURL":"",
    "CostCode":"P",
    "PublisherTemplate":"",
    "CropRatio":"",
    "XmPieCampaignID":"",
    "XmPieDocumentID":"",
    "WidthMM":514,
    "HeightMM":768,
    "FWidthMM":508,
    "FHeightMM":762,
    "DPI":300,
    "PixW":6071,
    "PixH":9071,
    "Price":"0"
  },
  {
    "ID":47,
    "GroupName":"Photocreate-Metal Prints",
    "ItemName":"Metal Prints",
    "Description":"30x40 Metal Print - Gloss",
    "UnitPrice":299.00,
    "Postage":21.83,
    "PCCode":1278,
    "DisplayOrder":04,
    "ItemMediaType":"",
    "MaxQuantity":"0",
    "DescriptionURL":"",
    "CostCode":"P",
    "PublisherTemplate":"",
    "CropRatio":"",
    "XmPieCampaignID":"",
    "XmPieDocumentID":"",
    "WidthMM":768,
    "HeightMM":1022,
    "FWidthMM":762,
    "FHeightMM":1016,
    "DPI":300,
    "PixW":9071,
    "PixH":12071,
    "Price":"0"
  },
  {
    "ID":48,
    "GroupName":"Photocreate-Notebooks",
    "ItemName":"Notepads - Notebooks",
    "Description":"Spiral Notebook Lined (200 pgs)",
    "UnitPrice":24.95,
    "Postage":3.37,
    "PCCode":654,
    "DisplayOrder":01,
    "ItemMediaType":"",
    "MaxQuantity":"0",
    "DescriptionURL":"",
    "CostCode":"P",
    "PublisherTemplate":"",
    "CropRatio":"",
    "XmPieCampaignID":"",
    "XmPieDocumentID":"",
    "WidthMM":171,
    "HeightMM":228,
    "FWidthMM":166,
    "FHeightMM":222,
    "DPI":300,
    "PixW":2020,
    "PixH":2693,
    "Price":"0"
  },
  {
    "ID":49,
    "GroupName":"Photocreate-FramedCanvasShaddowBox",
    "ItemName":"Framed Canvas in Shadow Box",
    "Description":"12x18 Black Framed Canvas in Shadow Box",
    "UnitPrice":119.00,
    "Postage":13.76,
    "PCCode":475,
    "DisplayOrder":01,
    "ItemMediaType":"",
    "MaxQuantity":"0",
    "DescriptionURL":"",
    "CostCode":"P",
    "PublisherTemplate":"",
    "CropRatio":"",
    "XmPieCampaignID":"",
    "XmPieDocumentID":"",
    "WidthMM":365,
    "HeightMM":515,
    "FWidthMM":300,
    "FHeightMM":450,
    "DPI":150,
    "PixW":2156,
    "PixH":3041,
    "Price":"0"
  },
  {
    "ID":50,
    "GroupName":"Photocreate-FramedCanvasShaddowBox",
    "ItemName":"Framed Canvas in Shadow Box",
    "Description":"12x18 White Framed Canvas in Shadow Box",
    "UnitPrice":119.00,
    "Postage":13.76,
    "PCCode":476,
    "DisplayOrder":02,
    "ItemMediaType":"",
    "MaxQuantity":"0",
    "DescriptionURL":"",
    "CostCode":"P",
    "PublisherTemplate":"",
    "CropRatio":"",
    "XmPieCampaignID":"",
    "XmPieDocumentID":"",
    "WidthMM":365,
    "HeightMM":515,
    "FWidthMM":300,
    "FHeightMM":450,
    "DPI":150,
    "PixW":2156,
    "PixH":3041,
    "Price":"0"
  },
  {
    "ID":51,
    "GroupName":"Photocreate-FramedCanvasShaddowBox",
    "ItemName":"Framed Canvas in Shadow Box",
    "Description":"12x18 Wood Framed Canvas in Shadow Box",
    "UnitPrice":119.00,
    "Postage":13.76,
    "PCCode":477,
    "DisplayOrder":03,
    "ItemMediaType":"",
    "MaxQuantity":"0",
    "DescriptionURL":"",
    "CostCode":"P",
    "PublisherTemplate":"",
    "CropRatio":"",
    "XmPieCampaignID":"",
    "XmPieDocumentID":"",
    "WidthMM":365,
    "HeightMM":515,
    "FWidthMM":300,
    "FHeightMM":450,
    "DPI":150,
    "PixW":2156,
    "PixH":3041,
    "Price":"0"
  },
  {
    "ID":52,
    "GroupName":"Photocreate-FramedCanvasShaddowBox",
    "ItemName":"Framed Canvas in Shadow Box",
    "Description":"16x20 Black Framed Canvas in Shadow Box",
    "UnitPrice":159.00,
    "Postage":15.29,
    "PCCode":478,
    "DisplayOrder":04,
    "ItemMediaType":"",
    "MaxQuantity":"0",
    "DescriptionURL":"",
    "CostCode":"P",
    "PublisherTemplate":"",
    "CropRatio":"",
    "XmPieCampaignID":"",
    "XmPieDocumentID":"",
    "WidthMM":465,
    "HeightMM":565,
    "FWidthMM":400,
    "FHeightMM":500,
    "DPI":150,
    "PixW":2746,
    "PixH":3337,
    "Price":"0"
  },
  {
    "ID":53,
    "GroupName":"Photocreate-FramedCanvasShaddowBox",
    "ItemName":"Framed Canvas in Shadow Box",
    "Description":"16x20 White Framed Canvas in Shadow Box",
    "UnitPrice":159.00,
    "Postage":15.29,
    "PCCode":479,
    "DisplayOrder":05,
    "ItemMediaType":"",
    "MaxQuantity":"0",
    "DescriptionURL":"",
    "CostCode":"P",
    "PublisherTemplate":"",
    "CropRatio":"",
    "XmPieCampaignID":"",
    "XmPieDocumentID":"",
    "WidthMM":465,
    "HeightMM":565,
    "FWidthMM":400,
    "FHeightMM":500,
    "DPI":150,
    "PixW":2746,
    "PixH":3337,
    "Price":"0"
  },
  {
    "ID":54,
    "GroupName":"Photocreate-FramedCanvasShaddowBox",
    "ItemName":"Framed Canvas in Shadow Box",
    "Description":"16x20 Wood Framed Canvas in Shadow Box",
    "UnitPrice":159.00,
    "Postage":15.29,
    "PCCode":480,
    "DisplayOrder":06,
    "ItemMediaType":"",
    "MaxQuantity":"0",
    "DescriptionURL":"",
    "CostCode":"P",
    "PublisherTemplate":"",
    "CropRatio":"",
    "XmPieCampaignID":"",
    "XmPieDocumentID":"",
    "WidthMM":465,
    "HeightMM":565,
    "FWidthMM":400,
    "FHeightMM":500,
    "DPI":150,
    "PixW":2746,
    "PixH":3337,
    "Price":"0"
  },
  {
    "ID":55,
    "GroupName":"Photocreate-FramedCanvasShaddowBox",
    "ItemName":"Framed Canvas in Shadow Box",
    "Description":"20x30 Black Framed Canvas in Shadow Box",
    "UnitPrice":219.00,
    "Postage":18.34,
    "PCCode":481,
    "DisplayOrder":07,
    "ItemMediaType":"",
    "MaxQuantity":"0",
    "DescriptionURL":"",
    "CostCode":"P",
    "PublisherTemplate":"",
    "CropRatio":"",
    "XmPieCampaignID":"",
    "XmPieDocumentID":"",
    "WidthMM":565,
    "HeightMM":815,
    "FWidthMM":500,
    "FHeightMM":750,
    "DPI":150,
    "PixW":3337,
    "PixH":4813,
    "Price":"0"
  },
  {
    "ID":56,
    "GroupName":"Photocreate-FramedCanvasShaddowBox",
    "ItemName":"Framed Canvas in Shadow Box",
    "Description":"20x30 White Framed Canvas in Shadow Box",
    "UnitPrice":219.00,
    "Postage":18.34,
    "PCCode":482,
    "DisplayOrder":08,
    "ItemMediaType":"",
    "MaxQuantity":"0",
    "DescriptionURL":"",
    "CostCode":"P",
    "PublisherTemplate":"",
    "CropRatio":"",
    "XmPieCampaignID":"",
    "XmPieDocumentID":"",
    "WidthMM":565,
    "HeightMM":815,
    "FWidthMM":500,
    "FHeightMM":750,
    "DPI":150,
    "PixW":3337,
    "PixH":4813,
    "Price":"0"
  },
  {
    "ID":57,
    "GroupName":"Photocreate-FramedCanvasShaddowBox",
    "ItemName":"Framed Canvas in Shadow Box",
    "Description":"20x30 Wood Framed Canvas in Shadow Box",
    "UnitPrice":219.00,
    "Postage":18.34,
    "PCCode":483,
    "DisplayOrder":09,
    "ItemMediaType":"",
    "MaxQuantity":"0",
    "DescriptionURL":"",
    "CostCode":"P",
    "PublisherTemplate":"",
    "CropRatio":"",
    "XmPieCampaignID":"",
    "XmPieDocumentID":"",
    "WidthMM":565,
    "HeightMM":815,
    "FWidthMM":500,
    "FHeightMM":750,
    "DPI":150,
    "PixW":3337,
    "PixH":4813,
    "Price":"0"
  },
  {
    "ID":58,
    "GroupName":"Photocreate-Mouse Mats",
    "ItemName":"Mouse Mats",
    "Description":"Deluxe Mouse Mat - Medium",
    "UnitPrice":24.95,
    "Postage":4.35,
    "PCCode":108,
    "DisplayOrder":01,
    "ItemMediaType":"",
    "MaxQuantity":"0",
    "DescriptionURL":"",
    "CostCode":"P",
    "PublisherTemplate":"",
    "CropRatio":"",
    "XmPieCampaignID":"",
    "XmPieDocumentID":"",
    "WidthMM":257,
    "HeightMM":210,
    "FWidthMM":248,
    "FHeightMM":199,
    "DPI":300,
    "PixW":3035,
    "PixH":2480,
    "Price":"0"
  },
  {
    "ID":59,
    "GroupName":"Photocreate-Keyrings",
    "ItemName":"Keyrings",
    "Description":"Rectangle Photo Keyring",
    "UnitPrice":4.95,
    "Postage":2.17,
    "PCCode":106,
    "DisplayOrder":01,
    "ItemMediaType":"",
    "MaxQuantity":"0",
    "DescriptionURL":"",
    "CostCode":"P",
    "PublisherTemplate":"",
    "CropRatio":"",
    "XmPieCampaignID":"",
    "XmPieDocumentID":"",
    "WidthMM":47,
    "HeightMM":37,
    "FWidthMM":45,
    "FHeightMM":35,
    "DPI":300,
    "PixW":555,
    "PixH":437,
    "Price":"0"
  },
  {
    "ID":60,
    "GroupName":"PhotoCreate-Canvas Prints",
    "ItemName":"Canvas Prints",
    "Description":"12x18 Canvas Print",
    "UnitPrice":69.95,
    "Postage":11.48,
    "PCCode":139,
    "DisplayOrder":01,
    "ItemMediaType":"",
    "MaxQuantity":"0",
    "DescriptionURL":"",
    "CostCode":"P",
    "PublisherTemplate":"",
    "CropRatio":"",
    "XmPieCampaignID":"",
    "XmPieDocumentID":"",
    "WidthMM":365,
    "HeightMM":515,
    "FWidthMM":300,
    "FHeightMM":450,
    "DPI":300,
    "PixW":4311,
    "PixH":6083,
    "Price":"0"
  },
  {
    "ID":61,
    "GroupName":"PhotoCreate-Canvas Prints",
    "ItemName":"Canvas Prints",
    "Description":"40x60 Canvas Print",
    "UnitPrice":419.00,
    "Postage":35.37,
    "PCCode":143,
    "DisplayOrder":05,
    "ItemMediaType":"",
    "MaxQuantity":"0",
    "DescriptionURL":"",
    "CostCode":"P",
    "PublisherTemplate":"",
    "CropRatio":"",
    "XmPieCampaignID":"",
    "XmPieDocumentID":"",
    "WidthMM":1065,
    "HeightMM":1565,
    "FWidthMM":1000,
    "FHeightMM":1500,
    "DPI":150,
    "PixW":6289,
    "PixH":9242,
    "Price":"0"
  }
];